name: release

on: workflow_dispatch

permissions:
  contents: read
  issues: write 

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USER: ${{ github.triggering_actor }}
      RELEASE_ID: ${{ github.run_number }}
      REGISTRY_ID: rgtgtrtrgtrgtrbt
      GH_TOKEN: ${{ secrets.TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run linters and tests
        run: |
          npm run lint
          npm run test

      - name: Update git config
        run: |
          git config --global user.name "$USER"
          git config --global user.email $USER@gmail.com
        
      - name: Create release branch
        run: |
          git checkout main
          git checkout -b release/$RELEASE_ID
        
      - name: Create tag
        run: git tag v$RELEASE_ID -m "v$RELEASE_ID"
  
      # - name: Build Docker image
      #   run: docker build . -t cr.yandex/$REGISTRY_ID/app:$RELEASE_ID -t cr.yandex/$REGISTRY_ID/app:$RELEASE_ID_latest

      - name: Create GitHub issue
        run: gh issue create --title "Release v$RELEASE_ID" --body "Date - $(date +%Y-%m-%d)"\
          "Version - $RELEASE_ID"\
          "Triggering actor - $USER"\
          "Last commits - $(git log --pretty=format:"%h - %an, %ar - %s" -10)"\
          "Image URL - cr.yandex/$REGISTRY_ID/app:$RELEASE_ID"
          
