name: release

on: workflow_dispatch

permissions:
  contents: read
  issues: write 

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USER: ${{ github.triggering_actor }}
      RELEASE: ${{ github.run_number }}
      REGISTRY: cr.yandex/registry/app
      GH_TOKEN: ${{ secrets.TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run linters and tests
        run: |
          npm run lint
          npm run test

      - name: Update git config
        run: |
          git config --global user.name "$USER"
          git config --global user.email $USER@gmail.com
        
      - name: Create tag
        run: |
          git checkout main
          git tag -a v$RELEASE -m "v$RELEASE"
        
      - name: Create release branch
        run: |
          git checkout -b release/$RELEASE
        
      - name: Build Docker image
        run: |
          docker build . -t ${{ env.REGISTRY }}:${{ env.RELEASE }} -t ${{ env.REGISTRY }}:${{ env.RELEASE }}_latest

      - name: Create GitHub issue
        run: |
          touch $FILE
          echo "**Version:** $RELEASE  " >> $FILE
          echo "**Date:** $(date +%Y-%m-%d)  " >> $FILE
          echo "**Triggering actor:** $USER  " >> $FILE
          echo "**Docker image:** $REGISTRY:$RELEASE  " >> $FILE
          echo "**Last commits:**  " >> $FILE
          git log v$(($RELEASE - 1)) ..HEAD --pretty=format:"%h - %an, %ar - %s   " >> $FILE
          gh issue create --title "Release $RELEASE_ID" --body-file $FILE
          rm $FILE
        env:
          FILE: issue.txt
          
      - name: Update CHANGELOG.md
        run: |
          touch $TEMP
          cat $FILE > $TEMP
          touch $FILE
          echo "Version: $RELEASE  " >> $FILE
          git log v$(($RELEASE - 1))..HEAD --pretty=format:"%h - %an, %ar - %s   " >> $FILE
          echo "    " >> $FILE
          cat $TEMP >> $FILE
          cat $FILE
          rm $TEMP
        env:
          FILE: CHANGELOG.md
          TEMP: TEMP_CHANGELOG.md
